config/routes.rb
Mysite::Application.routes.draw do

  root  "home#welcome"
  get '/home',:to=> 'home#home'
  get '/my_work',:to=> 'work_intro#index'
  get '/my_blog',:to=> 'blogs#index'
  get '/my_interest',:to=> 'interest#index'
  get '/my_book',:to=> 'my_book#index'
  get '/my_book/book_list',:to=> 'my_book#get_books'
  get '/my_book/find_book/:name',:to=> 'my_book#find_book'

  post '/my_blog/add_comment',:to=> 'blogs#add_comment'
  get '/my_blog/get_comment/:id',:to=> 'blogs#get_comment'
  get '/my_blog/find_by_offset/:offset',:to=> 'blogs#find_by_offset'
  get '/gallery',:to=> 'gallery#album'
  get '/album/:id',:to=> 'gallery#show'
  get '/album/:id/upload',:to=> 'gallery#create'
  get '/album/:id/:offset',:to=> 'gallery#get_more_photo'
  get '/gallery/get_pic',:to=> 'gallery#get_pic'
  get '/gallery/new',:to=> 'gallery#new'
  post '/gallery/new',:to=> 'gallery#new_create'
  post '/blogs/:id/like',:to=> 'blogs#like'
  post '/blogs/:id/dislike',:to=> 'blogs#dislike'

  resources :blogs
  resources :tags
  resources :books,:controller=>'my_book'
  resources :photos

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  has_many :blogTags
  has_many :tags, through: :blogTags
  has_many :comments
  has_attached_file :cover,
                    styles: {large: "1500x1500>" },
                    default_url: "/images/:style/missing.png",
                    :path => ":rails_root/public/images/blogs/:id.:extension",
                    :url  => "/images/blogs/:id.:extension"

  validates_attachment  :cover, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  protect_from_forgery :except => :create

  DATETIME_FORMAT = "%Y%m%d%H%M";

  def index
  end
  def new
  end
  def find_by_offset
    offset = params[:offset];
    if offset.nil?
      offset=0;
    end
    @blogs = Blog.all.limit(10).offset(offset).order("created_at desc");
    @blogs.each  do | blog|
      blog.content = blog.content.truncate(20);
      puts "---------->"+blog.content
    end
    render json: @blogs.to_json(include: :tags);
  end

  def show
    @article = Blog.find(params[:id]);
    @site_title  = @article.title
  end

  def get_comment
    @comments = Comment.where("blog_id"=>params[:id]).order("created_at desc");
    if params[:mode].nil?
      @comments.limit(2)
    end
    render json: @comments
  end

  def add_comment
    if params[:comment].length>0 && params[:name].length>0
      comment = Comment.new;
      comment.content=params[:comment]
      comment.name=params[:name]
      comment.blog_id=params[:id];
      comment.save
    end
    get_comment()
  end

  def create
    content = params[:blog][:content];
    title = params[:blog][:title];
    imgs = params[:blog][:imgs];
    tags = params[:tags];

    if !imgs.nil?
      imgs.each_with_index do |img,index|
        img_aligs =Time.now.strftime(DATETIME_FORMAT).to_s+img[:key];
        content.gsub(img[:key],"<img src='"+img_aligs+"' class='blog_img' />")
      end
    end
    tag_array = Array.new;
    puts tags

    if !tags.nil?
      tags.each_with_index do  |tag,index|
        if  tag.length > 0
          got_tag = Tag.find_by_name(tag);
          if got_tag.nil?
            got_tag = Tag.new
            got_tag.name = tag;
            got_tag.created_at = Time.now.strftime(DATETIME_FORMAT);
            got_tag.save;
          end
          tag_array[index] = got_tag
        end
      end
    end

    blog_raw = upload_params
    blog_raw[:title]= title
    blog_raw[:content]= content
    blog_raw[:tags]= tag_array
    blog = Blog.create(blog_raw);
    blog.created_at = Time.now.strftime(DATETIME_FORMAT);
    blog.updated_at = Time.now.strftime(DATETIME_FORMAT);
    blog.save;
    redirect_to("/my_blog")
  end

  def upload_params
    params[:blog].permit(:cover)
  end

  def like
    blog = Blog.find(params[:id])
    if blog.like.nil?
      blog.like =1
    else
      blog.like += 1
    end
    blog.save
    render :text=>blog.like, :layout=>false
  end

  def dislike
    blog = Blog.find(params[:id])
    if blog.dislike.nil?
      blog.dislike =1
    else
      blog.dislike += 1
    end
    blog.save
    render :text=>blog.dislike, :layout=>false
  end

end

app/helpers/blog_helper.rb
module BlogHelper
end

app/views/blogs/index.erb
<div class="blog_container" ng-controller="BlogCtrl">
  <section id="body_header" class="body_header">
    <div class="blog_header_space"></div>
    <div class="blog_title_box">
      <h1>{{lang.my_blog_title}}</h1>
      <nav class="blog_nav_box">
        <ul class="blog_nav_box_list">
          <li ng-click="loadBlogs()" >{{lang.my_blog_list}}</li> <li ng-click="loadTags()">{{lang.my_blog_category}} </li>
        </ul>
      </nav>
    </div>
  </section>
  <div class="gap_space">
  </div>
  <div class="display_area">
    <section ng-hide="hide_blog"  class="article_block" ng-repeat="blog in blogs">
      <div ng-if ="blog.created_date!=null" class="article_border"></div>
      <h2 class="artical_time">{{blog.created_date}}</h2>
      <h2 class="artical_title"><a href="/blogs/{{blog.id}}">{{blog.title}}</a></h2>
      <a href="/blogs/{{blog.id}}"><article class="article_content"  ng-bind-html="blog.content"></article></a>
      <div>
        <span ng-repeat="tag in blog.tags" class="article_tag"><a href="/tags/{{tag.id}}">{{tag.name}}</a></span>
      </div>
    </section>
    <nav ng-hide="hide_tag" class="article_block">
      <ul id="tag_block">
        <li ng-click="goto(tag.id)" class="tag_item" ng-repeat="tag in tags">
          <div><img src="/images/tag/{{tag.img}}" alt="lang" class="circular tag_img" ></div>
          <div class="tag_text"><h3><a href="/tags/{{tag.id}}">{{tag.name}}</a></h3></div>
        </li>
        <div class="clear"></div>
      </ul>
    </nav>
  </div>
</div>
<%= render partial: "shared/footer" %>
<%= javascript_include_tag "blog_list", "data-turbolinks-track" => true %>

app/views/blogs/new.erb
<div class="gap_space">
</div>
<div class="blog_container">
  <%= form_for :blog ,url: blogs_path do |blog| %>

      <div>
        <%= blog.label(:cover_label, "名称") %>
        <%= blog.text_field :title %>
      </div>
      <div>
        <%= blog.label(:cover_label, "内容") %>
        <%= blog.text_area :content, :style=>"width:40%;height:400px;" %>
      </div>
      <div>
        <%= blog.label(:cover_label, "标题图片") %>
        <%= blog.file_field :cover %>
      </div>
      <div>
        <%= blog.text_field :tag1, :name=>'tags[]' %>
        <%= blog.text_field :tag2, :name=>'tags[]'%>
        <%= blog.text_field :tag3, :name=>'tags[]' %>
      </div>
      <div>
        <%= blog.submit  %>
      </div>
  <% end %>
</div>

app/views/blogs/show.erb
<%= javascript_include_tag "blog_show", "data-turbolinks-track" => true %>
<div  class="alticle_container" ng-controller="ArticleCtrl" ng-init="get_comment( <%= @article.id %>)">
  <div ng-click="return()" class="back_button"><img src="/icon/right_arrow_w.gif"/></div>
  </a>
  <section id="body_header" bg-img="<%= @article.cover(:large) %>" class="article_header">
    <div class="header_blinder">
      <div class="article_header_space"></div>
      <div class="blog_title_box">
        <h1><%= @article.title %></h1>
      </div>
    </div>
  </section>
  <div class="gap_space">
  </div>

  <div id="display_area" class="display_area">
    <div id="display_area_wraper" class="display_area_wraper">
      <div class="vote_box">
        <div><button  ng-click="like(<%= @article.id %>)" class="vote_box_button">靠谱</button></div>
        <div id="like_count" class="like_count"><% if @article.like.nil?  %>0<% else %><%= @article.like %><% end %></div>
        <div><button  ng-click="dislike(<%= @article.id %>)" class="vote_box_button">不靠谱</button></div>
        <div id="dislike_count" class="like_count"><% if @article.dislike.nil?  %>0<% else %><%= @article.dislike %><% end %></div>
      </div>
      <section class="article_body">
        <article class="article_content">
          <%= simple_format(raw @article.content) %>
        </article>
        <nav class="article_tag_area">
          <% @article.tags.each do |tag| %>
              <span class="article_tag"><a href="/tags/<%= tag.id %>"><%= tag.name %></a></span>
          <% end %>
          <div class="clear"></div>
        </nav>
      </section>
      <div class="gap_space"><span class="comment_title">评论</span></div>
      <section class="comment_area" ng-repeat="comment in comments track by $index">
        <article ng-if="$index==comments.length-1" style="border-bottom: 0px solid" class="comment_item">
          <div style="font-weight: bold">{{comment.name}}</div>
          <span>{{comment.content}}</span>

          <div>{{comment.created_at}}</div>
        </article>
        <article ng-if="$index!=comments.length-1" class="comment_item">
          <div style="font-weight: bold">{{comment.name}}</div>
          <span>{{comment.content}}</span>

          <div>{{comment.created_at}}</div>
        </article>
      </section>
      <div class="comment_input">
        <input id="name_input" name="name" ng-model="name" type="text" ng-init="name='过客'">
        <input id="comment_input" placeholder="Put your comment" ng-model="comment" type="text">
        <span style="float:right"><a id="comment_button" class="button" href="#" ng-click="sendComment(<%= @article.id %>,comment,name)">添加评论</a></span>
        <div class="clear"></div>
      </div>
      <div class="clear"></div>
    </div>
  </div>
</div>
<%= render partial: "shared/footer" %>