config/routes.rb
Mysite::Application.routes.draw do

  root  "home#welcome"
  get '/home',:to=> 'home#home'
  get '/my_work',:to=> 'work_intro#index'
  get '/my_blog',:to=> 'blogs#index'
  get '/my_interest',:to=> 'interest#index'
  get '/my_book',:to=> 'my_book#index'
  get '/my_book/book_list',:to=> 'my_book#get_books'
  get '/my_book/find_book/:name',:to=> 'my_book#find_book'

  post '/my_blog/add_comment',:to=> 'blogs#add_comment'
  get '/my_blog/get_comment/:id',:to=> 'blogs#get_comment'
  get '/my_blog/find_by_offset/:offset',:to=> 'blogs#find_by_offset'
  get '/gallery',:to=> 'gallery#album'
  get '/album/:id',:to=> 'gallery#show'
  get '/album/:id/upload',:to=> 'gallery#create'
  get '/album/:id/:offset',:to=> 'gallery#get_more_photo'
  get '/gallery/get_pic',:to=> 'gallery#get_pic'
  get '/gallery/new',:to=> 'gallery#new'
  post '/gallery/new',:to=> 'gallery#new_create'
  post '/blogs/:id/like',:to=> 'blogs#like'
  post '/blogs/:id/dislike',:to=> 'blogs#dislike'

  resources :blogs
  resources :tags
  resources :books,:controller=>'my_book'
  resources :photos

end

app/models/album.rb
class Album < ActiveRecord::Base
  has_many :photos


  def cover
    self.photos.sample
  end

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  has_many :blogTags
  has_many :tags, through: :blogTags
  has_many :comments
  has_attached_file :cover,
                    styles: {large: "1500x1500>" },
                    default_url: "/images/:style/missing.png",
                    :path => ":rails_root/public/images/blogs/:id.:extension",
                    :url  => "/images/blogs/:id.:extension"

  validates_attachment  :cover, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }

end

app/models/blog_tag.rb
class BlogTag < ActiveRecord::Base
  belongs_to :blog
  belongs_to :tag
end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessor :img_url,:file_url
  has_attached_file :cover,
                    styles: {large: "1500x1500>" },
                    default_url: "/images/:style/missing.png",
                    :path => ":rails_root/public/images/book/:id.:extension",
                    :url  => "/images/book/:id.:extension"
  has_attached_file :file,
                    default_url: "javascript:alert('no resource is available')",
                    :path => ":rails_root/public/books/:id_:filename",
                    :url  => "/books/:id_:filename"


  validates_attachment  :cover, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
  validates_attachment  :file, content_type: { content_type: ["application/pdf", "application/txt", "application/mobi", "application/epub"] }


  def as_json(options = { })
    h = super(options)
    h[:img_url]   = cover(:large)
    h[:file_url]   = file(:large)
    h
  end



end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :blog
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :album
  has_attached_file :photo,
                    styles: {
                        #original: "3000x3000>",
                              large: "1500x1500>", medium: "700x700>", small: "300x300>", thumb: "100x100>" },
                    default_url: "/images/:style/missing.png",
                    :path => ":rails_root/public/photo/:id/:style/:filename",
                    :url  => "/photo/:id/:style/:filename"


  validates_attachment  :photo, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
end

app/models/tag.rb
class
Tag < ActiveRecord::Base
  has_many :blogTags
  has_many :blogs, through: :blogTags
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  protect_from_forgery :except => :create

  DATETIME_FORMAT = "%Y%m%d%H%M";

  def index
  end
  def new
  end
  def find_by_offset
    offset = params[:offset];
    if offset.nil?
      offset=0;
    end
    @blogs = Blog.all.limit(10).offset(offset).order("created_at desc");
    @blogs.each  do | blog|
      blog.content = blog.content.truncate(20);
      puts "---------->"+blog.content
    end
    render json: @blogs.to_json(include: :tags);
  end

  def show
    @article = Blog.find(params[:id]);
    @site_title  = @article.title
  end

  def get_comment
    @comments = Comment.where("blog_id"=>params[:id]).order("created_at desc");
    if params[:mode].nil?
      @comments.limit(2)
    end
    render json: @comments
  end

  def add_comment
    if params[:comment].length>0 && params[:name].length>0
      comment = Comment.new;
      comment.content=params[:comment]
      comment.name=params[:name]
      comment.blog_id=params[:id];
      comment.save
    end
    get_comment()
  end

  def create
    content = params[:blog][:content];
    title = params[:blog][:title];
    imgs = params[:blog][:imgs];
    tags = params[:tags];

    if !imgs.nil?
      imgs.each_with_index do |img,index|
        img_aligs =Time.now.strftime(DATETIME_FORMAT).to_s+img[:key];
        content.gsub(img[:key],"<img src='"+img_aligs+"' class='blog_img' />")
      end
    end
    tag_array = Array.new;
    puts tags

    if !tags.nil?
      tags.each_with_index do  |tag,index|
        if  tag.length > 0
          got_tag = Tag.find_by_name(tag);
          if got_tag.nil?
            got_tag = Tag.new
            got_tag.name = tag;
            got_tag.created_at = Time.now.strftime(DATETIME_FORMAT);
            got_tag.save;
          end
          tag_array[index] = got_tag
        end
      end
    end

    blog_raw = upload_params
    blog_raw[:title]= title
    blog_raw[:content]= content
    blog_raw[:tags]= tag_array
    blog = Blog.create(blog_raw);
    blog.created_at = Time.now.strftime(DATETIME_FORMAT);
    blog.updated_at = Time.now.strftime(DATETIME_FORMAT);
    blog.save;
    redirect_to("/my_blog")
  end

  def upload_params
    params[:blog].permit(:cover)
  end

  def like
    blog = Blog.find(params[:id])
    if blog.like.nil?
      blog.like =1
    else
      blog.like += 1
    end
    blog.save
    render :text=>blog.like, :layout=>false
  end

  def dislike
    blog = Blog.find(params[:id])
    if blog.dislike.nil?
      blog.dislike =1
    else
      blog.dislike += 1
    end
    blog.save
    render :text=>blog.dislike, :layout=>false
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def welcome
  end

  def home
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_upload, only: [:show, :edit, :update, :destroy]

  # GET /uploads
  # GET /uploads.json
  def index
    @uploads = Photo.all
  end

  # GET /uploads/1
  # GET /uploads/1.json
  def show
  end

  # GET /uploads/new
  def new
    @photo = Photo.new
  end

  # GET /uploads/1/edit
  def edit
  end

  # POST /uploads
  # POST /uploads.json
  def create
    file = upload_params;
    file[:album_id]=params[:photo][:album_id];
    @photo = Photo.create(file)

  end

  # PATCH/PUT /uploads/1
  # PATCH/PUT /uploads/1.json
  def update
    respond_to do |format|
      if @photo.update(upload_params)
        format.html { redirect_to @photo, notice: 'Upload was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uploads/1
  # DELETE /uploads/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to uploads_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_upload
    @photo = Photo.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def upload_params
    params[:upload].permit(:photo)
  end
end

app/controllers/tags_controller.rb
class TagsController  < ApplicationController

  def index
    @tags = Tag.all;
    render json: @tags
  end

  def show
    @tag = Tag.find(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
  def mobile_device?
    if session[:mobile_param]
      session[:mobile_param] == "1"
    else
      request.user_agent =~ /Mobile|webOS/
    end
  end
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/interest_helper.rb
module InterestHelper
end

app/helpers/my_blog_helper.rb
module MyBlogHelper
end

app/helpers/my_book_helper.rb
module MyBookHelper
end

app/helpers/my_work_helper.rb
module MyWorkHelper
end

app/helpers/uploader_helper.rb
module UploaderHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/work_intro_helper.rb
module WorkIntroHelper
end

app/views/home/home.erb
<div id="home_top_1" class="home_top_ " > </div>
<div id="top_page" ng-controller='HomeCtrl'>
<div class="home_top_box">
        <div id="home_title">
          <p>{{lang.home_welcome_slogan_1}}</p>
          <p style="font-size: 24px">{{lang.home_welcome_slogan_2}}</p>
        </div>
</div>
<!--<section class="home_bottom">-->
    <!--<article class="home_intro">-->
      <!--<p>-->
        <!--Hi, My name is He Yi, I am a software developer,this is my personal website, I've been thinking of Building a personal website for ages, finally started,-->
      <!--</p>-->
      <!--<p>-->
        <!--I will help you to know who I am here, I will share what I like, what I do, what I read, what I play and what I love here, hope you will like this website, and also like me in person-->

      <!--</p>-->
    <!--</article>-->
<!--</section>-->
<footer class="home_down">
    <div id='home_down_arrow' class="home_down_arrow">

    </div>
</footer>
</div>
<div  ng-controller='OptionCtrl' id="menu_area" class="menu_area">
    <div id='menu_list' class="menu_list">

      <div style="left: 10%" class="option_container">
        <div id='my_work' class="menu_list_item circular">
          <div oid='my_work' class="menu_list_item_cover circular"> </div>
        </div>
        <div id ="my_work_" class="menu_list_item_description circular"> {{lang.home_my_work}}</div>
      </div>
      <div style="left: 35%" class="option_container">
        <div id='my_blog' class="menu_list_item circular">
          <div oid='my_blog' class="menu_list_item_cover circular" > </div>
        </div>
        <div id ="my_blog_" class="menu_list_item_description circular">{{lang.home_my_blog}} </div>
      </div>
      <div style="left: 60%" class="option_container">
        <div id='my_book' class="menu_list_item circular">
          <div oid='my_book' class="menu_list_item_cover circular" > </div>
        </div>
        <div id ="my_book_" class="menu_list_item_description circular"> {{lang.home_my_book}}</div>
      </div>
      <div style="left: 85%" class="option_container">
        <div id='gallery' class="menu_list_item circular">
          <div oid='gallery' class="menu_list_item_cover circular" > </div>
        </div>
        <div id ="gallery_" class="menu_list_item_description circular">{{lang.home_gallery}} </div>
      </div>
    </div>
  <!--<div id="my_interest" class="menu_list_item">-->
  <!--<div class="menu_list_item_cover"></div>-->
  <!--</div>-->
    <div class="clear"></div>
</div>

app/views/home/welcome.erb
<div id='body' class="body welcome_bg">
<section class="welcome_box">
  <h1 class="welcome_content">
    Welcome to Yi's site
  </h1>
  <article class="entry_site">
    <div class="entry_block">
      <button id="enter" class="entry_button">ENTER</button>
    </div>
  </article>
</section>
</div>

app/views/photos/_form.html.erb
<%= form_for(@photo, html: { multipart: true }) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this upload from being saved:</h2>

      <ul>
        <% @photo.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.label :uploaded_file, t('.upload_new_file') %>
    <%= f.hidden_field :album_id, :value=>1 %>
    <%= f.file_field :uploaded_file, multiple: true, name: 'upload[uploaded_file]' %>
    <%= f.submit %>
  </div>
<% end %>

<% # jquery upload template # %>
<script id="template-upload" type="text/x-tmpl"><div class="upload">{%=o.name%}<div class="progress"><div class="progress-bar bar" style="width: 0%"></div></div></div></script>

app/views/photos/_upload.html.erb
<div class="uploaded_img">
<%= image_tag(@photo.photo(:small), class: 'thumb')  %>
</div>

app/views/photos/create.js.erb
<% if @photo.new_record? %>
  alert('Failed');
<% else %>
  if ($('#new_uploaded_img') !== undefined) {
    $('#new_uploaded_img').append("<%=j render partial: 'photos/upload', locals: { photo: @photo } %>");
  }
<% end %>

app/views/photos/edit.html.erb
<h1>Editing upload</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<h1>Listing uploads</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @uploads.each do |upload| %>
      <tr>
        <td><%= link_to 'Show', upload %></td>
        <td><%= link_to 'Edit', edit_photo_path(upload) %></td>
        <td><%= link_to 'Destroy', upload, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Upload', new_photo_path %>

app/views/photos/new.html.erb
<h1>New upload</h1>

<%= render 'form' %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<br />
<%= render 'upload' %>
<br />

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>

app/views/tags/show.erb
<div class="blog_container" bg-controller="TagCtrl">
  <section id="body_header" bg-img="/images/tag/<%=@tag.img %>" class="tag_header">
    <div class="header_blinder">
        <div class="tag_header_space"></div>
        <div class="blog_title_box">
          <h1 class="tag_title"><%= @tag.name %></h1>
        </div>
    </div>
  </section>
  <div class="gap_space">
  </div>
  <div class="display_area">
    <% @tag.blogs.each do |blog| %>
    <section class="article_block">
      <h2><a href="/blogs/<%=blog.id %>"><%=blog.title%></a></h2>
      <article class="article_content" ><a href="/blogs/<%=blog.id %>"><%=simple_format(raw blog.content)%></a></article>
    </section>
    <% end %>
  </div>
</div>
<%= render partial: "shared/footer" %>